### ISSUE TITLE
Deprecate call to handleRequests()

### ISSUE THREAD

**Issue by mpashkovskiy** [mpashkovskiy/express-oas-generator#81]
It is possible to do it by using https://stackoverflow.com/questions/47518962/specify-express-middleware-that-always-runs-at-the-end

Initial discussion is from: https://github.com/mpashkovskiy/express-oas-generator/issues/24#issuecomment-764469904

**Comment by kiprasmel** [comment]
I tried messing around for a while. Sadly, things didn't work (yet).

I tried:
- using `app.use((req, res, next)) => ...` + `res.once('finish', () => )` for handling both requests and responses
- using the same, but in `res.once('finish', () => )`, instead of reusing the same `req, res, next`, I tried passing in `res.app` and keeping the same logic for `handleResponses`.

I have not tried:
- wrapping `res.send` and handling things there.

dev branch: https://github.com/kiprasmel/express-oas-generator/tree/feat/unify-api-with-single-middleware-handler

I might mess around a bit more, but it probably be better if someone more experienced here like @mpashkovskiy took a shot:D

**Comment by maxiejbe** [comment]
@kiprasmel @mpashkovskiy let me take my shot 😄 Will let you know

**Comment by matveypashkovskiy** [comment]
go @maxiejbe 😄

**Comment by kiprasmel** [comment]
have fun 😄

**Comment by maxiejbe** [comment]
@mpashkovskiy @kiprasmel Here's the status guys:

The handler `res.once('finish', () => handleRequests())` inside `handleResponses` middleware seems to be working as expected.

We have another issue that probably blocks us to continue with this implementation:
The `handleRequests` function right initializes the spec (`serveApiDocs` function) by listing the express endpoints with [express-list-endpoints](https://www.npmjs.com/package/express-list-endpoints), in addition to applying the middleware.

In case we move that logic to the first middleware (handleResponses) the express routing is not yet ready and that **endpoints list would be empty**.

I tried attaching a handler with `app.on('listening', () => { // Initialize spec here})`, which I strongly discourage as it might be overwriting another listener.

So after all, we still need that last manual middleware 😄 

An alternative is to wait until the first request to initialize the spec and then start documenting the requests/responses.
The user won't be able to see the available endpoints until the first call is done.
I don't like it, but might be a solution.

What do you think?

**Comment by maxiejbe** [comment]
@mpashkovskiy @kiprasmel should we close this one and go back to #65 idea?

**Comment by kiprasmel** [comment]
@maxiejbe yeah I feel like this one isn't going anywhere anytime soon so I think we can focus on other things.

**Comment by mpashkovskiy** [comment]
I give it a try and looks like we, indeed, have to close it.
